spring.application.name=TaskManagerApplication

# --- REPLACE LOCAL MYSQL WITH H2 FOR DEMO ---
spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# --------------------------------------------

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=MyVerySecureJWTSecertKeyThatIsAtLeast32CharsLong12345
jwt.expiration=3600000

springdoc.swagger-ui.path=/swagger-ui.html
server.port=${PORT:8080}

spring.jackson.serialization.indent-output=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.setting.web-allow-others=true